version: '3.8'

services:
  mobile-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '32777:3000' # Map the container port 3000 to your local port 3000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/alert_mobile_db
    volumes:
      - .:/app
      - /app/node_modules # Prevent node_modules from being overwritten by the volume
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: mobile-backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydatabase
    ports:
      - '0:5432'
    volumes:
      - mobile-backend-db-data:/var/lib/postgresql/data

volumes:
  mobile-backend-db-data:
